name: l10n

  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 6'

jobs:
  l10n:
    uses: nvdaes/nvdaAddonWorkflows/.github/workflows/l10n.yaml@main
    