name: Lint diff

on:
  pull_request:
    branches:
      - main

jobs:

  diff:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint
      run: |
        git diff -U0 origin/main...HEAD -- addon/. > flake8.diff
        type flake8.diff | flake8 --diff --output-file=flake8.txt --tee
