name: Upload on new tags

on:
  push:
    tags:
      '*'

jobs:
  buildAndUpload:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scons
        pip install Markdown
    - name: Add add-on version
      run: |
        import re
        with open("buildVars.py", 'r+', encoding='utf-8') as f:
          text = f.read()
          version = "${{ github.ref }}".split("/")[-1]
          text = re.sub("\"addon_version\" : ,", "\"addon_version\" : \"%s\",", text) % version
          f.seek(0)
          f.write(text)
          f.truncate()
      shell: python 
    - name: Build add-on
      run: scons
    - name: Create Release
          - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.nvda-addon
